// Query to show all nodes in the Neo4j graph
MATCH (n)
RETURN 
    labels(n) AS node_labels,
    n.name AS name,
    n.namespace AS namespace,
    n.runId AS run_id,
    n.versionId AS version_id,
    n.datasetVersionId AS dataset_version_id,
    n.txHash AS transformation_hash,
    n.type AS type,
    n.subtype AS subtype,
    n.description AS description,
    n.language AS language,
    n.url AS url,
    n.repoUrl AS repo_url,
    n.path AS path,
    n.version AS version,
    n.tag AS tag,
    n.branch AS branch,
    n.processingType AS processing_type,
    n.integration AS integration,
    n.jobType AS job_type,
    n.contentType AS content_type,
    n.key AS key,
    n.value AS value,
    n.source AS source,
    n.masking AS masking,
    n.state AS state,
    n.prevNamespace AS prev_namespace,
    n.prevName AS prev_name,
    n.rowCount AS row_count,
    n.fileCount AS file_count,
    n.size AS size,
    n.programmingLanguage AS programming_language,
    n.stackTrace AS stack_trace,
    n.externalQueryId AS external_query_id,
    n.eventType AS event_type,
    n.eventTime AS event_time,
    n.createdAt AS created_at,
    n.updatedAt AS updated_at,
    n.schemaHash AS schema_hash,
    n.lifecycleState AS lifecycle_state,
    n.gitRef AS git_ref,
    n.codeHash AS code_hash,
    n.mode AS mode,
    id(n) AS node_id
ORDER BY labels(n), n.name 